.\" Manpage for example
.\" Contact me at location

.TH man 8 "06 May 2010" "1.0" "example man page"

.SH NAME
WHAT IS THE NAME

.SH SYNOPSIS
WHAT IS SYNOPSIS

.SH DESCRIPTION
WHAT IS DESCRIPTION
[WHAT IS THAT]
{THIS IS WHAT}

var i = 'okei'

int i = 10;

void example() {
  printf("THIS IS A TEXT %d \n", 30);
}

.SH SEE ALSO
WHAT IS SEE ALSO

.SH BUGS
WHAT IS BUGS

.SH AUTHOR
WHO IS AUTHOR

.SH COPYRIGHT
WHAT IS COPYRIGHT

.SH CODE
var i = 'okei';
